---
- name: Test Windows Connection
  hosts: windows_servers
  gather_facts: no
  
  tasks:
    - name: Test WinRM connection
      win_ping:
      
    - name: Get Windows version
      win_shell: |
        $PSVersionTable.PSVersion
        systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
      register: win_version
      
    - name: Display Windows info
      debug:
        msg: "{{ win_version.stdout_lines }}"
